apiVersion: v1
kind: Service
metadata:
    name: webserver-service
spec:
    type: NodePort
    ports:
        - nodePort: 30126
          port: 80
          targetPort: 80
    selector: 
        app: httpd