version: '3'
services:
    docker-mysql:
        container_name: docker-mysql
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: ProductCouponDB
            MYSQL_ROOT_PASSWORD: Root@123
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - "6666:3306"
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=Root@123 --execute \"SHOW DATABASE\""
            internal: 4s
            timeout: 20s
            retries: 5