version: '3'
services:
    web: 
        image: httpd
        container_name: mywebserver
        networks:
            - webnetwork
        ports:
            - "8080:80"
        volumes:
            - myvol:/data
networks: 
    webnetwork:
        driver: bridge
    dbnetwork:
        driver: bridge
volumes:
    myvol:

        